name = "SISL"
repo = "https://github.com/sisl/Registry.jl"
uuid = "b2c3bf37-fff5-4e76-b608-87f77ec6f5d6"
description = "Registry for SISL Julia packages"

[packages.44eeaf0b-fee4-471f-9310-ed6585cb3142]
name = "Vec"
path = "V/Vec"

[packages.99497e54-f3d6-53d3-a3a9-fa9315a7f1ba]
name = "AutomotiveDrivingModels"
path = "AutomotiveDrivingModels"

[packages.5984c134-fa48-5ed5-a57f-fc2f6936871f]
name = "Records"
path = "R/Records"
