name = "SISL"
repo = "https://github.com/sisl/Registry"
uuid = "b2c3bf37-fff5-4e76-b608-87f77ec6f5d6"
description = "Registry for SISL Julia packages"

[packages.44eeaf0b-fee4-471f-9310-ed6585cb3142]
name = "Vec"
path = "V/Vec"

[packages.99497e54-f3d6-53d3-a3a9-fa9315a7f1ba]
name = "AutomotiveDrivingModels"
path = "A/AutomotiveDrivingModels"

[packages.9ec66b5e-c605-11e8-1454-ede748df6f96]
name = "AutomotiveSensors"
path = "A/AutomotiveSensors"

[packages.1385418a-9289-5a49-ab93-843b508de4cb]
name = "AutoUrban"
path = "A/AutoUrban"

[packages.5984c134-fa48-5ed5-a57f-fc2f6936871f]
name = "Records"
path = "R/Records"

[packages.dca8afc0-c686-11e8-0934-712707da73aa]
name = "AutomotivePOMDPs"
path = "A/AutomotivePOMDPs"

[packages.82aa6e0c-a491-5edf-8d4b-c16b98e4ea17]
name = "AutoViz"
path = "A/AutoViz"
